spring:
  application:
    name: second-microservice
server:
  port:
    8082
eureka:
  instance:
    hostname: localhost
    port: 9000
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka